"""add start_date and end_date to courses

Revision ID: d_add_dates_to_courses
Revises: c_add_active_sessions
Create Date: 2025-10-24 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd_add_dates_to_courses'
down_revision = 'c_add_active_sessions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('courses', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'end_date')
    op.drop_column('courses', 'start_date')
    # ### end Alembic commands ###
