"""add file_path to documents

Revision ID: e_add_file_path_to_documents
Revises: d_add_dates_to_courses
Create Date: 2025-10-24 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e_add_file_path_to_documents'
down_revision = 'd_add_dates_to_courses'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'url', existing_type=sa.Text(), nullable=True)
    op.add_column('documents', sa.Column('file_path', sa.String(500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_path')
    op.alter_column('documents', 'url', existing_type=sa.Text(), nullable=False)
    # ### end Alembic commands ###
